#!/bin/sh

function pluginstall () {
	git clone https://github.com/hexisXz/bzsh-plugins-source/tree/main/plugins-src/dnf

	cd dnf

	mv dnf.plug ~/.config/bzsh/plugins

	echo "source ~/.config/bzsh/plugins/dnf.plug" >> ~/.config/bzsh/bzsh-plug

	echo "how to use the dnf plugin:\n
	      dna: autoremove

	      dnc: clean

	      dnd: downgrade

	      dnh: dnf history

	      dni: dnf install

	      dns: dnf search

	      dnu: dnf upgrade"
}


[[ "command -v dnf 2>/dev/null" ]] && installplug || echo "ERROR: this plugin will not work on your system!"

 
